### ISSUE TITLE
[BUG] cant compile eaglerreborn beta

### ISSUE THREAD

**Issue by radmanplays** [EaglerReborn/EaglerReborn#108]
**Describe the bug**
when i try to compile eaglerreborn beta it gives me an error

**To Reproduce**
1. use build_make_workspace.bat or build_make_workspace.sh to make a workspace
2. go to the workspace
3. open a terminal and type ./gradlew teavm
4. it gives you this error :

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :compileJava
/mnt/c/Users/HOME/Downloads/EaglerReborn-beta-v1.0/eaglercraft_1.8_workspace/src/main/java/net/zxmushroom63/plugins/PluginConstructors.java:30: error: cannot find symbol
            return ItemStack.fromPluginData(data).makePluginData();
                            ^
  symbol:   method fromPluginData(BaseData)
  location: class ItemStack
/mnt/c/Users/HOME/Downloads/EaglerReborn-beta-v1.0/eaglercraft_1.8_workspace/src/main/java/net/zxmushroom63/plugins/PluginConstructors.java:36: error: cannot find symbol
            return BlockPos.fromPluginData(data).makePluginData();
                           ^
  symbol:   method fromPluginData(BaseData)
  location: class BlockPos
/mnt/c/Users/HOME/Downloads/EaglerReborn-beta-v1.0/eaglercraft_1.8_workspace/src/main/java/net/zxmushroom63/plugins/PluginConstructors.java:39: error: cannot find symbol
            return Vec3i.fromPluginData(data).makePluginData();
                        ^
  symbol:   method fromPluginData(BaseData)
  location: class Vec3i
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 12s
1 actionable task: 1 executed

**Expected behavior**
compile the client with no errors

**Browser (please complete the following information):**
 - OS: windows (using wsl)
 - Version: beta-v-1.0

**Comment by OtterCodes102** [comment]
I am unable to reproduce this. Are you sure you are using the latest commit?

**Comment by radmanplays** [comment]
> I am unable to reproduce this. Are you sure you are using the latest commit?

yeah i downloaded it from the releases tab

**Comment by wxnnvs** [comment]
try running powershell as administrator and do ./gradlew teavm again
this is how i do it

**Comment by radmanplays** [comment]
> use `git clone https://github.com/EaglerReborn/EaglerReborn`

i needed to reinitialize build_init

**Comment by ZXMushroom63** [comment]
So you can build now?

**Comment by radmanplays** [comment]
> So you can build now?

yeah
