### ISSUE TITLE
Help with developing a plugin

### ISSUE THREAD

**Issue by wxnnvs** [EaglerReborn/EaglerReborn#109]
I was trying to write a godmode plugin using the disableDamage property of the players capabilities.
it doesn't work lol
this is my current code:
```
PluginAPI.require("player");
var godMode = false;
window.addEventListener("keypress", (event) => {
  if (event.key.toLowerCase() === "g") {
    godMode = !godMode;
    PluginAPI.player.disableDamage = godMode;
    PluginAPI.updateComponent('player');
  }
});
```

**Comment by ZXMushroom63** [comment]
...
`PluginAPI.player.disableDamage = godMode;` should be `PluginAPI.player.capabilities.disableDamage = godMode;`

**Comment by wxnnvs** [comment]
Alr thx

**Comment by ZXMushroom63** [comment]
lol

**Comment by wxnnvs** [comment]
seems to crash my game

**Comment by wxnnvs** [comment]
it breaks when i added the displayToChat

**Comment by wxnnvs** [comment]
nvm i forgot ;
