### ISSUE TITLE
Pointer lock issue on Safari

### ISSUE THREAD

**Issue by olivia1246** [EaglerReborn/EaglerReborn#41]
This seems to overall a Eaglercraft Issue because the only version that had it working was Eaglercraft Beta 1.3

(MacBook Air M2 with Safari 16.5.2)

**Comment by OtterCodes101** [comment]
I will look into this.

**Comment by OtterCodes101** [comment]
This appears to just be an issue with Safari itself. Hopefully Apple will provide a fix.

**Comment by olivia1246** [comment]
Okay thank you. I will close this now (Sorry for the late response I haven't been on GitHub for a while)
