### ISSUE TITLE
it didnt let me join java servers

### ISSUE THREAD

**Issue by WINRARisyou** [EaglerReborn/EaglerReborn#48]
anytime i tried to join a java server it said connection refused or outdated server. it might have to do with via version idk

**Comment by WINRARisyou** [comment]
me from 2 minutes later, tried joining another server and got this"
![image](https://github.com/EaglerReborn/EaglerReborn/assets/99762912/dc8c589e-585b-4fea-bb7d-b55f75bf3c74)

**Comment by OtterCodes101** [comment]
this error means that the server does not exist.

**Comment by WINRARisyou** [comment]
um no i tried joining servers that existed and it said connection refused on all of them, only one of them game me the error listed above. itried joining: jartex.fun, play.pika-network.net, zentic.cc (i just tired zentic when i couldn't join any java servers) and twerion.net
