### ISSUE TITLE
still cant join java servers

### ISSUE THREAD

**Issue by WINRARisyou** [EaglerReborn/EaglerReborn#50]
![image](https://github.com/EaglerReborn/EaglerReborn/assets/99762912/71980f5c-c34e-44e1-a583-c2da50d7b2a8)

and i tried joining servers that existed and it said connection refused or outdated client on all of them, i tried joining: jartex.fun, play.pika-network.net, zentic.cc (i just tired zentic when i couldn't join any java servers) and twerion.net idk if i compiled it wrong or somthing. i even made a 1.8.8 server on aternos and tried that, and it tried to connect for longer and then just said connection lost.

**Comment by WINRARisyou** [comment]
wait i just tried joining play.verise.xyz and it worked for some reason

**Comment by OtterCodes101** [comment]
yeah this is in indev, meaning that only specific servers work for whatever reason. I'll try to get to it soon.

**Comment by OtterCodes101** [comment]
It's not even a client issue, its an issue with the working viaeagx version i used.

**Comment by WINRARisyou** [comment]
yo wait, when i used the reborn relay from replit and manually set the version to 1.12.2, it said no vpns allowed which is not good but it means im connecting now.

i used this ip: wss://reborn-relay--otterdev.repl.co/play.pika-network.net._v1_12_2._udjsakd._of

it showed me this: 
![image](https://github.com/EaglerReborn/EaglerReborn/assets/99762912/b53a4e01-ff5f-497b-aea9-9d64f9877e49)

**Comment by OtterCodes101** [comment]
This is because Eagler Reborn works by having a relay to translate Websocket to TCP. This means that the server detects it as a VPN.

**Comment by WINRARisyou** [comment]
at least with 1.12 it detects im joining the server. i havent tried other versions yet but 1.8.x does not work

**Comment by OtterCodes101** [comment]
version issue fixed in e7884b5
