### ISSUE TITLE
make the plugins menu more... Minecrafty

### ISSUE THREAD

**Issue by radmanplays** [EaglerReborn/EaglerReborn#78]
![image](https://github.com/EaglerReborn/EaglerReborn/assets/95340057/549e5a22-0927-4d31-956e-6899ac5d368b)

**Comment by OtterCodes101** [comment]
lmao you should really be asking @ZXMushroom63

**Comment by OtterCodes101** [comment]
anyway this is because the plugin menu was written in javascript, not java

**Comment by ZXMushroom63** [comment]
yep! either way, i could probably try to give it a background with dirt blocks, but the font might have to stay.

**Comment by ZXMushroom63** [comment]
right, made it more minecrafty
![Screenshot 2023-09-03 160014](https://github.com/EaglerReborn/EaglerReborn/assets/116805577/99b0ba26-a8c7-4aa3-8635-32c025335cb6)

**Comment by ZXMushroom63** [comment]
it'll be out in a4.1

**Comment by radmanplays** [comment]
> it'll be out in a4.1

k

**Comment by Orphanlol** [comment]
amazing

**Comment by OtterCodes101** [comment]
a4.1 released
