### ISSUE TITLE
Ladders

### ISSUE THREAD

**Issue by MegaTheLEGEND** [EaglerReborn/EaglerReborn#84]
**Describe the bug**

Ladders don't work in game. they glitch weirdly. if you press "s" while using a ladder in a 1x1 hole it functions correctly. (this happens in all eaglercraftX clients) 

**To Reproduce**
1. Go to any server
2. Attempt to climb a ladder. 

**Expected behavior**

I expected to climb the ladder. 

**Screenshots**

**Browser (please complete the following information):**
 - OS: I was testing on windows but has the same problem on all.
 - Browser: chrome/any
 - Version: Alpha?

**Comment by ZXMushroom63** [comment]
Just tested this, but it only appears to fail when using the spacebar.

As far as I know, walking in to the ladder (facing it and just holding down W) is the correct way to climb a ladder in 1.8
