### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by MHAKittens** [EaglerReborn/EaglerReborn#85]
I would like Anime Mode like what they had in the recent client, I'm not asking for much. Me and my friends have a good laugh every time it pops up. Please make my Eagler Reborn Experience better. Have a good day. But if you do it, add more please.

**Comment by radmanplays** [comment]
> I would like Anime Mode like what they had in the recent client, I'm not asking for much. Me and my friends have a good laugh every time it pops up. Please make my Eagler Reborn Experience better. Have a good day. But if you do it, add more please.

if anyone wants to add anime mode ive extracted the anime mode assets from resent client. if anyone wants to use it here it is : https://easyupload.io/0l69ea

**Comment by OtterCodes101** [comment]
no
