### ISSUE TITLE
Java servers dont recognize EaglerReborn as a valid 1.8.x client.

### ISSUE THREAD

**Issue by ItsDoomOne** [EaglerReborn/EaglerReborn#88]
The servers that I play don't allow EaglerReborn to work because "Invalid Version: use 1.8.x to 1.20.x"
I think its a problem with the version identifier, maybe changing removing the Alpha or something

**Comment by OtterCodes101** [comment]
no such thing as a version identifier, also this is done client side

**Comment by OtterCodes101** [comment]
one sec lemme make a fix rq
