### ISSUE TITLE
[BUG] plugin makes eagler reborn crash

### ISSUE THREAD

**Issue by radmanplays** [EaglerReborn/EaglerReborn#93]
**Describe the bug**
when i try to join a server with [this](https://raw.githubusercontent.com/radmanplays/eaglerreborn-plugins/main/slipperiness.js) plugin eagler reborn crashes. heres the crash report : 
Eagler Reborn has crashed!

Shall we play a game?

---- Minecraft Crash Report ----
// eagler

Time: Sep 5, 2023
Description: Ticking entity

java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of undefined (reading 'getBlock')
	at TypeError: Cannot read properties of undefined (reading 'getBlock')
	at data:text/javascript;base64,UGx1Z2luQVBJLnJlcXVpcmUoIkJsb2NrRGF0YSIpOwoKUGx1Z2luQVBJLmFkZEV2ZW50TGlzdGVuZXIoInVwZGF0ZSIsICgpID0+IHsKICAvLyBHZXQgdGhlIGJsb2NrIHVuZGVyIHRoZSBwbGF5ZXIncyBmZWV0CiAgY29uc3QgYmxvY2tVbmRlclBsYXllciA9IFBsdWdpbkFQSS53b3JsZC5nZXRCbG9jayhQbHVnaW5BUEkucGxheWVyLngsIFBsdWdpbkFQSS5wbGF5ZXIueSAtIDEsIFBsdWdpbkFQSS5wbGF5ZXIueik7CgogIC8vIENoZWNrIGlmIHRoZSBibG9jayBoYXMgc2xpcHBlcmluZXNzIHByb3BlcnR5CiAgaWYgKGJsb2NrVW5kZXJQbGF5ZXIgaW5zdGFuY2VvZiBCbG9ja0RhdGEpIHsKICAgIGNvbnN0IHNsaXBwZXJpbmVzcyA9IGJsb2NrVW5kZXJQbGF5ZXIuc2xpcHBlcmluZXNzOwoKICAgIC8vIEFwcGx5IHNsaXBwZXJpbmVzcyB0byBwbGF5ZXIncyBtb3ZlbWVudAogICAgUGx1Z2luQVBJLnBsYXllci5tb3Rpb25YICo9IHNsaXBwZXJpbmVzczsKICAgIFBsdWdpbkFQSS5wbGF5ZXIubW90aW9uWiAqPSBzbGlwcGVyaW5lc3M7CgogICAgLy8gVXBkYXRlIHRoZSBwbGF5ZXIncyBtb3Rpb24KICAgIFBsdWdpbkFQSS51cGRhdGVDb21wb25lbnQoInBsYXllciIpOwogIH0KfSk7Cg==:5:44
	at file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:16658:276
	at Array.forEach (<anonymous>)
	at Object.callEvent (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:16658:253)
	at A.A0P (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:16661:38)
	at A.JA (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:16655:282)
	at A.Ot (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:21481:281)
	at $rt_array.toString [as dq] (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:31734:19)
	at B6G (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:22019:143)
	at CrF (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:22016:143)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at TypeError: Cannot read properties of undefined (reading 'getBlock')
	at data:text/javascript;base64,UGx1Z2luQVBJLnJlcXVpcmUoIkJsb2NrRGF0YSIpOwoKUGx1Z2luQVBJLmFkZEV2ZW50TGlzdGVuZXIoInVwZGF0ZSIsICgpID0+IHsKICAvLyBHZXQgdGhlIGJsb2NrIHVuZGVyIHRoZSBwbGF5ZXIncyBmZWV0CiAgY29uc3QgYmxvY2tVbmRlclBsYXllciA9IFBsdWdpbkFQSS53b3JsZC5nZXRCbG9jayhQbHVnaW5BUEkucGxheWVyLngsIFBsdWdpbkFQSS5wbGF5ZXIueSAtIDEsIFBsdWdpbkFQSS5wbGF5ZXIueik7CgogIC8vIENoZWNrIGlmIHRoZSBibG9jayBoYXMgc2xpcHBlcmluZXNzIHByb3BlcnR5CiAgaWYgKGJsb2NrVW5kZXJQbGF5ZXIgaW5zdGFuY2VvZiBCbG9ja0RhdGEpIHsKICAgIGNvbnN0IHNsaXBwZXJpbmVzcyA9IGJsb2NrVW5kZXJQbGF5ZXIuc2xpcHBlcmluZXNzOwoKICAgIC8vIEFwcGx5IHNsaXBwZXJpbmVzcyB0byBwbGF5ZXIncyBtb3ZlbWVudAogICAgUGx1Z2luQVBJLnBsYXllci5tb3Rpb25YICo9IHNsaXBwZXJpbmVzczsKICAgIFBsdWdpbkFQSS5wbGF5ZXIubW90aW9uWiAqPSBzbGlwcGVyaW5lc3M7CgogICAgLy8gVXBkYXRlIHRoZSBwbGF5ZXIncyBtb3Rpb24KICAgIFBsdWdpbkFQSS51cGRhdGVDb21wb25lbnQoInBsYXllciIpOwogIH0KfSk7Cg==:5:44
	at file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:16658:276
	at Array.forEach (<anonymous>)
	at Object.callEvent (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:16658:253)
	at A.A0P (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:16661:38)
	at A.JA (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:16655:282)
	at A.Ot (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:21481:281)
	at $rt_array.toString [as dq] (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:31734:19)
	at B6G (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:22019:143)
	at CrF (file:///C:/Users/HOME/Downloads/EaglerReborn-main/eaglercraft_1.8_workspace/javascript/EaglercraftX_1.8_Offline_International.html:22016:143)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 1550
	Entity Name: aaa
	Entity's Exact location: 210.39, 64.00, 214.70
	Entity's Block location: 210.00,64.00,214.00 - World: (210,64,214), Chunk: (at 2,4,6 in 13,13; contains blocks 208,0,208 to 223,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of null (reading 'constructor')
	Entity's Vehicle: ~~ERROR~~ java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of null (reading 'constructor')

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['aaa'/1550, l='MpServer', x=210.39, y=64.00, z=214.70]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 175.00,64.00,229.00 - World: (175,64,229), Chunk: (at 15,4,5 in 10,14; contains blocks 160,0,224 to 175,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1384667 game time, 1433777 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['aaa'/1550, l='MpServer', x=210.39, y=64.00, z=214.70]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- PaperSpigot
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: TeaVM (null) version null
	Java Version: 1.8, null
	Java VM Version: null (null), null
	Launched Version: 1.8.8
	LWJGL: EagRuntimeX 1.0
	OpenGL: ANGLE (Intel, Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0, D3D11) GL version WebGL 2.0 (OpenGL ES 3.0 Chromium), Google Inc. (Intel)
	Is Modded: well no not in the traditional sense
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)

eaglercraft.version = "u17"
eaglercraft.minecraft = "1.8.8"
eaglercraft.brand = "Eagler Reborn"
eaglercraft.username = "aaa"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = ANGLE (Intel, Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0, D3D11)
webgl.vendor = Google Inc. (Intel)

window.eaglercraftXOpts = {"container":"game_frame","relayURL":"wss://reborn-relay.otterdev.repl.co","servers":[{"addr":"wss://mercurymc.net","name":"MercuryMC"}],"assetsURI":[{"url":"data:application/octet-stream;base64,RUFHUEtHJCQGdmVyMi4wCmFzc2V0cy5lcGsAWAoKICMgIEVhZ2xlciBFUEsgdjIuMCAoYykgPz8/PyBsYXgxZHVkZQogIyAgdXBkYXRlOiBvbiA/Py8/Py8/Pz8/IGF0ID8/Oj8/Oj8/ID8/Pz8/Pz8/CgoAAAGKXF9E0AAADoRHH4sIAAAAAAAC/+xdCVxU1fdHc0FcwCVDQ33gAugwDIKKuA4wwNDA4MwgovHPNzOP4clszZthMXMlf6aI+5pLpqBmapZlmjullrukZm6VKe6WuaRm/M+9773ZWNTk1+/3/3/k5y9g3n3nnnPvOd9zz7nnXhIk4thGmbSeCrHmmykPD4+mlDk71EIxJptFQzH946QySRuSYSgrE0qROj1lCY1RSGKlKqXQmmf18HjTp6BO0C4JfkIoKLXJYiRiqRxKbzJTFsZrdDVfXl5ecquVskDTUPxDjElLMWGisCgvwosIIWIsFGk1WQjSqCX0FKkltDxNwpRJuHSHmmvgbS2httF6awhtJCyUnswnmHzGShmgp6FDkmxMlsVkMvQM5+inWUxWirBmUYRZb9PBK2xj3J84RYqaiLWIJkkw2bQZSFutJiORCSyhlxgrabESjMZCUUZ/xxeRZsr1hw69OA41FjLTOsR5PIhqx4PQk3lhWpuWwhw6DYFdXkwNP2K5T0gjSI2GgiekFTiVmyljvIwIE4YTlMGmR+86NSb1ehhDJttqMnOPaZAHjRtulGKyIBpItiTaSOGugFQkodHTlBFEtWgIq4lQUeTgJCeqzmJG24w6inJ6iEeXtGqy8KiiydHycwISkvk2I2mgu4tEIl7iJNKYD+10RCadRzH4I3YSeHUEcpps5wfsDMBzjcmipY0650cUadBTDENk2vR6tp1jWDlRLZRZT1vxhCH9I2wMPMilrVmgEG46NrqGL/S+F9H5Gb/QOykW0whKYyWSSQMVRQyWiklS6fhUbLNmmSzwOU0OBuWBCXM8S1XIoogsq9XMRIWG5tBkDttAqAPubWohbQrlqXkRqUisOERJgQ1DaZ+ErvCPkNEayoia2IxaitXv+ORUQpyZSVlMRDxlBAXTEyk2tZ7W8I2JnHChSIjeTqEsBppBfTNIVWHsGDAPiwmUgbGCgpnz9RTokp57j7RQ8KFRSyP9gz5BCQ1kNkwdQeaQtJ5U69Fzg1lPgQZxs460FNHW84zmmizZDNYqg0lLZ9IarM2MgMjNokHdaKNGD4YEFmXRgUBsaxuDO3ElInCSmYE54J8KQR/M+RZal2VlIYjj3miywk8MYbCBbGrQR9BMypJDadELRquFBpwwWRj43JRDAwekkaDyUCOG0FlIsCOQAkwCWRQmzgiJtCxQYJITBNjiJpKgGVYdwers1AjUGTBAmKAV/GqkrKwUiP/qRg09q0SdF8BAIrr8yAuRTtSOLnNI4a7KYj2VR+UTYqMWDDKnGnW2UmSOQWiy6EJdtTcGJKT1aBoTgWU0MolKAZGokBA0Et0Aw4oVAWu20wx2F4VFuPUsrF73xQAy8I17IiA40yO6C0VEEGoQwD0KCO6DSOSbbDCM+Ug30IyxFoA8Kky9hjJbQR3ZuaFJI0wLghfcD0cFG1E6R8OktpI0UgdkN/zk8SZHWjmm8RcaLBir3NxcIYk5xgPGKSoTKpPGSJKVkhDgmnsr1Yjh0EK9aaMtyFvmE6QZuNJgm9OTuQTytzoYHax0wEauBazUqBOARmVac8FyERktzbB67jJoPI8gunMDGDYwgQCxkpAqA4hosVKqFCAiaVJVgjxVRaSJFQpxskoqURJyBREjT4aFhVSeDL/FEeLkdOI1aXKsgKBgyKAf3pKATTTfoM547JQU5cKC3UebKQ3CBhDNqLOROorQIbMxIv0xO4EW2Dcio6cNNKs+TGW5hLVjFLK0RPDQ4ZXNQmkmGboaa0AzrM8dodOjCXY1CNblC/B3MXxHUBUvi0sj1LQRuUMGzSLv9bUUcq0Wm9FKGyh3EwnSBCMz6R6CEQ3gSYY+zqXwQ2xt8QgeZbTaQlry0btiWFCwGEbYQZDTNAVl1wEaa4AWGwZaZbHQhNcDtBEoodkyIOBGVgETh76bbEjRXaBdgP0GnjUr0isOEZEXJ614ojJNer0pF82t3bswBKeyBsoaxbEW4sYc9lnOgImB0UJhM0R0STUoDTZHLCxrfqwbELCmrgdyiIpzv0atG1PQp0ZPwsBbhNVyAj06DQrPCYiqtWmofw8zBCslS0hr0tjsGIpeC0WrT2x6BvBZFprUM46Rt+OYsxAO4ZI5o0UtjKzq1KBQIISjKZoTliMalEvj7FcRRqopu2OkjFr4lEKKA3wZ0KKTHS54DyyYBp1kCWXCU25pwkEZr2kOmDBbaKSAFqRhRieE4GVSJUiVh…

**Comment by ZXMushroom63** [comment]
this is a bug in your plugin, not the API or EaglerReborn

I am also assuming that you are using your `slipperiness.js` plugin, which I noticed has `PluginAPI.world.getBlock`.
I have not yet implemented the world yet. Also, it looks like you used some java code in there, judging by the `instanceof`.
The PluginAPI is in JavaScript, meaning I have to manually implement every feature.

However, if you want an easy method to quickly make every block have a set slipperiness value, try this:
```
var blockKeys = Object.keys(PluginAPI.blocks);
blockKeys.forEach(key=>{
   PluginAPI.blocks[key].slipperiness = 2; //Anything, really.
});
```

**Comment by radmanplays** [comment]
> this is a bug in your plugin, not the API or EaglerReborn
> 
> I am also assuming that you are using your `slipperiness.js` plugin, which I noticed has `PluginAPI.world.getBlock`. I have not yet implemented the world yet. Also, it looks like you used some java code in there, judging by the `instanceof`. The PluginAPI is in JavaScript, meaning I have to manually implement every feature.
> 
> However, if you want an easy method to quickly make every block have a set slipperiness value, try this:
> 
> ```
> var blockKeys = Object.keys(PluginAPI.blocks);
> blockKeys.forEach(key=>{
>    if(PluginAPI?.blocks?.[key]?.slipperiness) {// TeaVM likes to add metadata properties which are `null` or `undefined`
>       PluginAPI.blocks[key].slipperiness = 0.98; //Ice slipperiness value.
>       PluginAPI.blocks[key].reload(); //The new method, `PluginAPI.updateComponent` is obsolete now.
>    }
> });
> ```

it dosnt work : 
[screen-capture (4).webm](https://github.com/EaglerReborn/EaglerReborn/assets/95340057/c837a6e0-6627-4630-a297-bdecea0f65a0)

**Comment by ZXMushroom63** [comment]
Minecraft calculates slipperiness in a very strange way. I recommend just leaving it at 0.98, (ice) but I tested it and it worked perfectly.
0.6 - Ground Blocks
0.98 - Ice Blocks

**Comment by radmanplays** [comment]
> Minecraft calculates slipperiness in a very strange way. I recommend just leaving it at 0.98, (ice) but I tested it and it worked perfectly. 0.6 - Ground Blocks 0.98 - Ice Blocks

this is what it looks like with 0.98 slipperiness and eagler reborn beta 1.0 :
[Eagler Reborn Beta 1.0 - aaa - 2023-09-16 05-13-19.webm](https://github.com/EaglerReborn/EaglerReborn/assets/95340057/c21b98ba-dd79-4b79-8d97-b3a630b4c18e)

**Comment by ZXMushroom63** [comment]
Right, im gonna test this.

**Comment by ZXMushroom63** [comment]
Just tried this exact code:
```
var blockKeys = Object.keys(PluginAPI.blocks);
blockKeys.forEach(key=>{
   if(PluginAPI?.blocks?.[key]?.slipperiness) {// TeaVM likes to add metadata properties which are `null` or `undefined`
      PluginAPI.blocks[key].slipperiness = 0.98; //Ice slipperiness value.
      PluginAPI.blocks[key].reload(); //The new method, `PluginAPI.updateComponent` is obsolete now.
   }
});
```
and it worked.

**Comment by radmanplays** [comment]
> Just tried this exact code:
> 
> ```
> var blockKeys = Object.keys(PluginAPI.blocks);
> blockKeys.forEach(key=>{
>    if(PluginAPI?.blocks?.[key]?.slipperiness) {// TeaVM likes to add metadata properties which are `null` or `undefined`
>       PluginAPI.blocks[key].slipperiness = 0.98; //Ice slipperiness value.
>       PluginAPI.blocks[key].reload(); //The new method, `PluginAPI.updateComponent` is obsolete now.
>    }
> });
> ```
> 
> and it worked.

why is it broken for me then?

**Comment by ZXMushroom63** [comment]
Try only using this plugin, and nothing else.
Otherwise, try to use a different testing server, or update your EaglerReborn.
I'm honestly not sure. You could try just pasting it in the console like I did.

**Comment by radmanplays** [comment]
> Try only using this plugin, and nothing else. Otherwise, try to use a different testing server, or update your EaglerReborn. I'm honestly not sure. You could try just pasting it in the console like I did.

oh it works now! it seems like it was issue in Eagler Reborn alpha

**Comment by ZXMushroom63** [comment]
ok
